### ISSUE TITLE
Error loading native library "/app/bin/Debug/netcoreapp3.0/runtimes/linux/native/libfaiss_c.so

### ISSUE THREAD

**Issue by AhmadSabbahgh** [roxima/faisssharp#1]
I'm trying to run faisssharp on Docker but its showing me this error:
![image](https://user-images.githubusercontent.com/4170668/74613082-e9fb2400-5113-11ea-9973-943f857c37ac.png)

I've downloaded the repo, added docker support to IndexFlatL2, here is the docker file:
FROM mcr.microsoft.com/dotnet/core/runtime:3.0-buster-slim AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.0-buster AS build
WORKDIR /src
COPY ["examples/IndexFlatL2/IndexFlatL2.csproj", "examples/IndexFlatL2/"]
COPY ["FaissSharp/FaissSharp.csproj", "FaissSharp/"]
RUN dotnet restore "examples/IndexFlatL2/IndexFlatL2.csproj"
COPY . .
WORKDIR "/src/examples/IndexFlatL2"
RUN dotnet build "IndexFlatL2.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "IndexFlatL2.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "IndexFlatL2.dll"]

I'm running Docker Desktop on Windows but I made sure its using Linux images.

**Comment by roxima** [comment]
This repository is actually not mine and is cloned for convenience, it is merely a mirror of [this](https://gitlab.com/josetruyol/faisssharp). You'd be better to create an issue there.
